server:
  port: 8080

spring:
  datasource:
    name: springboot_login
    url: jdbc:mysql:///springboot_login?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=UTC
    #    url: jdbc:mysql://localhost:3306//springboot?characterEncoding=utf8
    username: root
    password: 123456



    # 使用druid数据源
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  #    filters: stat
  #      maxActive: 20
  #      initialSize: 1
  #      maxWait: 60000
  #      minIdle: 1
  #      timeBetweenEvictionRunsMillis: 60000
  #      minEvictableIdleTimeMillis: 300000
  #      validationQuery: select 'x'
  #      testWhileIdle: true
  #      testOnBorrow: false
  #      testOnReturn: false
  #      poolPreparedStatements: true
  #      maxOpenPreparedStatements: 20

  ## Redis 配置
  redis:
    database: 0
    #Redis服务器地址，默认localhost
    host: localhost
    #Redis服务器端口，默认6379
    port: 6379
    password:
    pool:
      #连接池最大连接数
      max-active: 8
      #最大阻塞等待时间，-1表示没有限制
      max-wait: -1
      #最大空闲连接
      max-idle: 8
      #最小空闲连接
      min-idle: 0
    #连接超时时间
    timeout: 120000

  resources:

    static-locations: classpath:/templates  #访问静态页面

mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.company.corporation.springboot.springbootlogin.entity  # 注意：对应实体类的路径
